/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.spsisys.scoreboard;

import com.spsisys.scoreboard.exceptions.TeamIsPlayingException;
import com.spsisys.scoreboard.entities.Team;
import com.spsisys.scoreboard.entities.Game;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
