/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.spsisys.scoreboard;

import com.spsisys.scoreboard.entities.Game;
import com.spsisys.scoreboard.entities.Team;
import com.spsisys.scoreboard.exceptions.TeamIsPlayingException;
import com.spsisys.scoreboard.stores.WCScoreBoardStoreMgr;
import com.spsisys.scoreboard.services.WCScoreBoardService;
import com.spsisys.scoreboard.services.WCScoreBoardServiceMgr;

import java.util.List;

public class Library {

    private final WCScoreBoardService service;

    public Library() {
        this.service = new WCScoreBoardServiceMgr(new WCScoreBoardStoreMgr());
    }

    // 1. Start a game
    public Game startGame(Team homeTeam, Team awayTeam) throws TeamIsPlayingException {
        return this.service.startGame(homeTeam, awayTeam);
    }

    // 2. Finish game
    public void finishGame(Game game) {
        this.service.finishGame(game.getHomeTeam(), game.getAwayTeam());
    }

    public void finishGame(Team homeTeam, Team awayTeam) {
        this.service.finishGame(homeTeam, awayTeam);
    }

    // 3. Update score
    public void updateScore(Team homeTeam, Team awayTeam, int homeScore, int awayScore) {
        this.service.updateScore(homeTeam, awayTeam, homeScore, awayScore);
    }

    public void updateScore(Game game, int homeScore, int awayScore) {
        this.service.updateScore(game.getHomeTeam(), game.getAwayTeam(), homeScore, awayScore);
    }

    // 4. Get a summary of games by total score
    public List<Game> getSummary() {
        return this.service.getSummary();
    }

    public String getSummaryAsString() {
        return this.service.getSummaryAsString();
    }
}
